export const TIPOS_DOCUMENTO_CORPORATIVO = [
  "Acta constitutiva",
  "Reformas",
  "Poder del representante legal",
  "Constancia de Situación Fiscal",
  "Identificación oficial",
  "Comprobante de domicilio",
  "Datos bancarios",
  "Opinión de cumplimiento fiscal (32-D)",
  "Cumplimiento IMSS",
  "Cumplimiento INFONAVIT",
  "Declaración de integridad",
  "Manifestación de no impedido",
  "Información de socios/accionistas",
  "Escrito de personalidad",
  "Declaración de nacionalidad",
  "Estratificación MIPYME",
  "Documentación RUPC",
  "Otro",
];
